---
vg_build: 31
# This will be replaced by jenkins.
build_tag:  vggp-v##-j##-##-branch

cloud: bwCloud

galaxy_uid: 999
galaxy_gid: 999

telegraf_agent_tags:
  - tag_name: datacenter
    tag_value: rz
  - tag_name: cloud
    tag_value: "{{ cloud }}"
  - tag_name: vgcn_build
    tag_value: "{{ build_tag }}"
  - tag_name: distribution
    tag_value: "{{ ansible_distribution }}"
  - tag_name: distribution_version
    tag_value: "{{ ansible_distribution_version }}"

telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: diskio
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: netstat
  - plugin: processes
  - plugin: kernel
  - plugin: chrony
  - plugin: exec
    config:
      - commands = ["/bin/iamalive"]
      - name_suffix = "_alive"

java_packages:
 - java-11-openjdk

cvmfs_role: client

dynmotd_custom: []

nodejs_version: "8.x"
nodejs_install_npm_user: root


texlive_directory: /usr/local/texlive
texlive_mirror: "http://packages.oth-regensburg.de/ctan/systems/texlive/tlnet/"
texlive_rsync: "rsync://packages.oth-regensburg.de/ctan/systems/texlive/tlnet/"
scheme: full
