---
- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - patch
    - lsof
    - screen
    - ansible
    - vim
    - collectl
    - iotop
    - iftop
    - htop
    - atop
    - mosh
    - libcgroup-tools
    - autofs
    - bind-utils
    - strace
    - nfs-utils
    - "@development"
    - jq
    - pdsh
    # Fonts
    - dejavu-fonts-common
    - dejavu-sans-fonts
    - fontconfig
    - fontconfig-devel
    - fontpackages-filesystem
    - ghostscript-fonts
    - libXfont
    - liberation-fonts-common
    - liberation-sans-fonts
    - libfontenc
    - urw-fonts
    - xorg-x11-font-utils
    - at
    - perl-Digest-SHA
    - telnet
    - python-pip
    - wget
    - perl-Digest-MD5

- name: Ensure services are enabled + started
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - atop
    - autofs
    - atd

- name: yum-autoupdate removal
  yum: name=yum-autoupdate state=absent

# https://www.freedesktop.org/software/systemd/man/journald.conf.html#Storage=
# The "auto" option defaults to dropping data if a magic directory doesn't
# exist. We switch this to persistent because that's the desired behaviour.
- name: Fix journald default
  lineinfile:
    dest: /etc/systemd/journald.conf
    line: "Storage=persistent"
    regexp: "^.*Storage=.*"

- name: Upload utils
  copy:
    src: '{{ item }}'
    dest: '/usr/bin/{{ item }}'
    mode: 0755
    owner: root
    group: root
  with_items:
    - colordiff
    - timestamped

- name: Install ranger
  pip:
    name: ranger-fm
